[package]
name = "rickboard"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
pixels = "0.15"
rayon = "1.10"
image = "0.25"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
